create database DataPokokSMK;

use DataPokokSMK;

CREATE TABLE SEKOLAH (
	NPSN INT,
    NAMA_SMK TEXT NOT NULL,
    STATUS_SMK CHAR(6),
    ALAMAT TEXT,
    NO_TELP INT NULL,
    KODE_POS INT(5),
    PRIMARY KEY (NPSN)
);

CREATE TABLE ALAMAT (
	NPSN INT(8) UNSIGNED,
	KODE_POS INT(5),
	KELURAHAN TEXT,
    KECAMATAN TEXT,
    KABUPATEN_KOTA TEXT,
    PROVINSI TEXT,
    PRIMARY KEY (NPSN, KODE_POS),
	foreign key (NPSN) REFERENCES SEKOLAH(NPSN)
);

CREATE TABLE KEAHLIAN (
	NPSN INT(8) UNSIGNED,
	KODE_BIDANG INT(4),
    ID_BIDANG INT(2), 
    BIDANG_KEAHLIAN TEXT,
    primary key (KODE_BIDANG, NPSN),
    foreign key (NPSN) REFERENCES SEKOLAH(NPSN)
);

CREATE TABLE BIDANG (
	KODE_BIDANG INT(4) UNSIGNED,
    ID_BIDANG INT(2),
    BIDANG_KEAHLIAN TEXT,
    KODE_PROGRAM INT(4) UNSIGNED,
    ID_PROGRAM INT(2),
    PROGRAM_KEAHLIAN TEXT,
    PRIMARY KEY (KODE_PROGRAM, KODE_BIDANG),
	foreign key (KODE_BIDANG) REFERENCES KEAHLIAN(KODE_BIDANG)
);

CREATE TABLE PROGRAM (
	KODE_PROGRAM INT(4) unsigned,
    ID_PROGRAM INT unsigned zerofill NOT NULL,
    PROGRAM_KEAHLIAN TEXT,
    ID_KOMPETENSI INT unsigned zerofill NOT NULL,
    KOMPETENSI_KEAHLIAN TEXT,
    PRIMARY KEY (KODE_PROGRAM),
	foreign key (KODE_PROGRAM) REFERENCES BIDANG(KODE_PROGRAM)
);

INSERT INTO SEKOLAH (NAMA_SEKOLAH)
VALUES ('SMK STEMIK YMB TANJUNG BUKA'), ('SMK TERPADU CITRA BANGSA'), ('SMK TRIDAYA PRATAMA'), ('SMK-SPP NEGERI MALINAU'), ('SMKN 1 BUNYU');

INSERT INTO SEKOLAH (NPSN)
VALUES ('69929128'), ('69933671'), ('69903627'), ('30407391'), ('69911762');

INSERT INTO SEKOLAH (STATUS_SMK)
VALUES ('Swasta'), ('Swasta'), ('Swasta'), ('Negeri'), ('Negeri');

INSERT INTO SEKOLAH (ALAMAT)
VALUES ('JL. DESA TANJUNG BUKA , Kel.Salim Batu, Kec. Kec. Tanjung Palas Tengah'), ('JL. DAMAI BAKTI , Kel.Karang Harapan, Kec. Kec. Tarakan Barat'), 
('JL. DAMAI BAKTI, Kel.Karang Harapan, Kec. Kec. Tarakan Barat'), ('JL. SEKOLAH 1.100 , Kel.Binai, Kec. Kec. Tanjung Palas Timur'), ('JL. LADANG , Kel.Malinau Seberang, Kec. Kec. Malinau Utara');

INSERT INTO SEKOLAH (NO_TLP)
VALUES ('085279679100'), ('085389548908'), ('085389548908'), ('069903627'), ('081346388484');

INSERT INTO SEKOLAH (KODE_POS)
VALUES ('77253'), ('77118'), ('77118'), ('77215'), ('77554');

INSERT INTO ALAMAT (KELURAHAN)
VALUES ('SALIM BATU'), ('KARANG HARAPAN'), ('KARANG HARAPAN'), ('BINAI'), ('MALINAU SEBERANG');

INSERT INTO ALAMAT (KABUPATEN_KOTA)
VALUES ('KAB. BULUNGAN'), ('KOTA TARAKAN'), ('KOTA TARAKAN'), ('KAB. BULUNGAN'), ('KAB. MALINAU');

INSERT INTO ALAMAT (PROVINSI)
VALUES ('KALIMANTAN UTARA'), ('KALIMANTAN UTARA'), ('KALIMANTAN UTARA'), ('KALIMANTAN UTARA'), ('KALIMANTAN UTARA');

INSERT INTO ALAMAT (KODE_POS)
VALUES ('77253'), ('77118'), ('77118'), ('77215'), ('77554');

INSERT INTO KEAHLIAN (KODE_BIDANG)
VALUES ('0201'), ('0404'), ('0120'), ('0501'), ('0501');

INSERT INTO KEAHLIAN (ID_BIDANG)
VALUES ('02'), ('04'), ('01'), ('05'), ('05');

INSERT INTO KEAHLIAN (BIDANG_KEAHLIAN)
VALUES ('TEKNOLOGI INFORMASI & KOMUNIKASI'), ('KESEHATAN & PEKERJAAN SOSIAL'), ('TEKNOLOGI DAN REKAYASA'), ('AGRIBISNIS & AGROTEKNOLOGI'), ('AGRIBISNIS & AGROTEKNOLOGI');

INSERT INTO KEAHLIAN (NPSN)
VALUES ('69929128'), ('69933671'), ('69903627'), ('30407391'), ('69911762');

INSERT INTO BIDANG (ID_PROGRAM)
VALUES ('01'), ('04'), ('20'), ('01'), ('01');

INSERT INTO BIDANG (PROGRAM_KEAHLIAN)
VALUES ('TEKNIK KOMPUTER & INFORMATIKA'), ('FARMASI'), ('TEKNIK OTOMOTIF'), ('AGRIBISNIS PRODUKSI TANAMAN'), ('AGRIBISNIS PRODUKSI TANAMAN');

INSERT INTO BIDANG (KODE_BIDANG)
VALUES ('0201'), ('0404'), ('0120'), ('0501'), ('0501');

INSERT INTO BIDANG (ID_BIDANG)
VALUES ('02'), ('04'), ('01'), ('05'), ('05');

INSERT INTO BIDANG (BIDANG_KEAHLIAN)
VALUES ('TEKNOLOGI INFORMASI & KOMUNIKASI'), ('KESEHATAN & PEKERJAAN SOSIAL'), ('TEKNOLOGI DAN REKAYASA'), ('AGRIBISNIS & AGROTEKNOLOGI'), ('AGRIBISNIS & AGROTEKNOLOGI');

INSERT INTO PROGRAM (ID_KOMPETENSI)
VALUES ('03'), ('01'), ('11'), ('03'), ('02');

INSERT INTO PROGRAM (KOMPETENSI_KEAHLIAN)
VALUES ('TEKNIK KOMPUTER & JARINGAN'), ('FARMASI KLINIS & KOMUNITAS'), ('TEKNIK OTOMOTIF KENDARAAN RINGAN'), ('AGRIBISNIS TANAMAN PERKEBUNAN'), ('AGRIBISNIS TANAMAN PANGAN DAN HOLTIKULTURA');

INSERT INTO PROGRAM (ID_PROGRAM)
VALUES ('01'), ('04'), ('20'), ('01'), ('01');

INSERT INTO PROGRAM (PROGRAM_KEAHLIAN)
VALUES ('TEKNIK KOMPUTER & INFORMATIKA'), ('FARMASI'), ('TEKNIK OTOMOTIF'), ('AGRIBISNIS PRODUKSI TANAMAN'), ('AGRIBISNIS PRODUKSI TANAMAN');